import Ember from 'ember';
import MarkerLayer from 'high-ground/components/marker-layer';
import computed from 'ember-computed-decorators';
import { alias, equal } from 'ember-computed-decorators';

const {
  inject: { service },
  observer
} = Ember;

export default MarkerLayer.extend({

  geolocation: service(),

  @alias('geolocation.lat') lat,
  @alias('geolocation.lng') lng,

  createLayer() {
    let geolocation = this.get('geolocation');
    let array = geolocation.getArray();
    let accuracy = geolocation.get('accuracy');
    return L.userMarker(array, {
      accuracy,
      smallIcon: true,
      pulsing: true
    });
  },

  // this should be based on an event generated by geolocation service
  onLocationChange: observer('lat', 'lng', function() {
    let geolocation = this.get('geolocation');
    let array = geolocation.getArray();
    let accuracy = geolocation.get('accuracy');
    this._layer.setLatLng(array);
    this._layer.setAccuracy(accuracy);
  })

});